config/routes.rb
Rails.application.routes.draw do
  resources :projects do
    resources :items, :only => [:new, :create, :edit, :update]
    delete 'clear', :on => :member
  end
  root 'projects#index'
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :project
  validates :action,
    :presence => true,
    :uniqueness => { :scope => :project,
    				 :unless => -> { !Item.where(:action => self.action, :cleared => nil).where.not(:id => self.id).present?},
                     :message => 'should be unique within a project' }
  validates :project_id, :presence => true
  scope :complete, -> { where(:done => true) }
end

app/models/project.rb
class Project < ActiveRecord::Base
  validates :title, :presence => true,
  :uniqueness => { :scope => :title,
                     :message => 'must be unique' }
  has_many :items, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_filter :get_project

  def new
    @item = @project.items.build
  end

  def create
    @item = @project.items.build(item_params)

    respond_to do |format|

      if @item.save
        format.html { redirect_to project_path(@project),
                      :notice => 'Item was successfully created.' }
      else
          format.html { redirect_to project_path(@project),
                      :notice => @item.errors.full_messages.to_sentence }
      end
    end
  end

  def edit
    @item = @project.items.find(params[:id])
  end

  def update
    @item = @project.items.find(params[:id])

    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to project_path(@project),
                      :notice => 'Item was successfully updated.' }
      else
        format.html { render :action => 'edit' }
      end
    end
  end

private

  def get_project
    @project = Project.find(params[:project_id])
  end

  def item_params
    params.require(:item).permit(:action, :done)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, :except => [:index, :new, :create]

  def index
    @projects = Project.all
  end

  def show
     @item = Item.new 
  end

  def new
    @project = Project.new
  end

  def edit
  end

  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_path(@project),
                      :notice => 'Project was successfully created.' }
      else
        format.html { render :action => 'new' }
      end
    end
  end

  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_path(@project),
                      :notice => 'Project was successfully updated.' }
      else
        format.html { render :action => 'edit' }
      end
    end
  end

  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_path,
                    :notice => 'Project was successfully destroyed.' }
    end
  end

  def clear
    if @project.items.complete.where(cleared: nil).count > 0
    @project.items.complete.update_all(cleared: true)
    respond_to do |format|
      format.html { redirect_to project_path(@project),
                    :notice => 'Completed items were successfully cleared.' }
    end
  else
    respond_to do |format|
      format.html { redirect_to project_path(@project),
                    :notice => 'There are no completed items for this project.' }
  end
end
end

private
  def set_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type.to_sym] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} alert-dismissible", role: 'alert') do
        concat(content_tag(:button, class: 'close', data: { dismiss: 'alert' }) do
          concat content_tag(:span, '&times;'.html_safe, 'aria-hidden' => true)
          concat content_tag(:span, 'Close', class: 'sr-only')
        end)
        concat message
      end)
    end
    nil
  end
end

app/views/items/_index.html.erb
<%= render template: "items/new" %>             
                    <hr>
                    <ul id="sortable" class="list-unstyled">
                    <% if @project.items.empty? %>
                    <li class="ui-state-default">
                        <div class="checkbox">
                            <label>
                                <input type="checkbox" value="" />No Items, You should add some!</label>
                        </div>
                    </li>
                    <% end %>

                   <% total = @project.items.where(cleared: nil , done: false).each do |item| %>
                    <li class="ui-state-default">

                             <%= link_to '<i class="fa fa-check"></i>'.html_safe,
                              { :controller => :items, :action => :update,
                              :id => item.id, :project_id => @project.id,
                                :item => { :done => true } },
                              { :method => :patch }%>
                                            
                                <%= link_to item.action, edit_project_item_path(@project, item) %>
     
                    </li>
                    <% end %>
 

                <div class="todo-footer">
                    <strong><span class="count-todos"><%= total.count %></span></strong> Items Left
                </div>
            </div>
        </div>

        <div class="col-md-6">
            <div class="todolist">
             <h1>Already Done</h1>
                <ul id="done-items" class="list-unstyled">
                <% @project.items.where(cleared: nil , done: true).each do |item| %>
                    <li><%= link_to item.action, edit_project_item_path(@project, item) %></li>
                    <% end %>
                    
                </ul>
                <%= link_to 'Clear Completed Items', clear_project_path(project),
      :method => :delete, :id => "clearer" %>
            </div>
        </div>

app/views/items/edit.html.erb
<h2>Edit Item</h2>
<%= form_for([@project, @item], :url => { :action => :update }) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@item.errors.count, "error") %>
        prohibited this project from being saved:
      </h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :action %><br>
    <%= f.text_field :action, :class => 'form-control add-todo' %>
  </div>
  <div class="field">
    <%= f.label :done, 'Done?' %>
    <%= f.check_box :done %>
  </div>
  <div class="actions">
    <%= f.submit :class => 'btn btn-success'%>
  </div>
<% end %>

app/views/items/new.html.erb
<%= form_for([@project, @item]) do |f| %>

  <div class="field">
    <%= f.text_field :action, :class => 'form-control add-todo', :placeholder => 'Add todo item' %>
  </div>
  <div class="actions">
    <%= f.submit :class => 'btn btn-success'%>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <!--[if lt IE 9]>
    <script src="http://html5.shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <title>Todo App</title>
    <%= stylesheet_link_tag "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
      <!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <p class="navbar-brand">Todo App</p>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to 'Projects', projects_path %></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

 <div class="container-fluid">
    <div class="row">

      <%= flash_messages %>

      <%= yield %>

     </div>
</div>

    <div class="footer">
    <div class="container-fluid">
      <p>2015 - PhishMe Homework App</p>
      </div>
    </div>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@project.errors.count, "error") %>
        prohibited this project from being saved:
      </h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, :class => 'form-control add-todo' %>
  </div>
  <div class="actions">
    <%= f.submit :class => 'btn btn-success' %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<div class="todolist">
<h1>Edit Project</h1>

<%= render 'form' %>
</div>

app/views/projects/index.html.erb
<div class="todolist">
<h1>All Projects <small> <%= link_to 'New Project', new_project_path %> </small></h1>

<ul>
  <% if @projects.empty? %>
  <li>No projects.</li>
  <% end %>
<% @projects.each do |project| %>
<li><h3>
  <%= link_to project.title, project_path(project) %>
  <span>
    <%= link_to "<small><i class=\"fa fa-trash-o\"></i></small>".html_safe, project,
                method: :delete, data: { confirm: 'Are you sure?' } %>
  </span>
  </h3>
</li>
<% end %>
</ul>


</div>

app/views/projects/new.html.erb
<div class="todolist">
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>
</div>

app/views/projects/show.html.erb
        <div class="col-md-6">
            <div class="todolist not-done">             
<h1><%= link_to @project.title, edit_project_path(@project) %> Items</h1>
<%= render :partial => 'items/index', :locals => { :project => @project } %>